"""Make username unique again

Revision ID: a169417d8e48
Revises: c56396b62735
Create Date: 2024-08-08 03:34:48.915627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a169417d8e48'
down_revision: Union[str, None] = 'c56396b62735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_task_user', 'privilege', ['t_id', 'u_id'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint('uix_task_user', 'privilege', type_='unique')
    # ### end Alembic commands ###
